#!/usr/bin/python

from __future__ import print_function

import sys
import argparse
from secret_split import Secret_Split

def main () :
    cmd = argparse.ArgumentParser ()
    cmd.add_argument \
        ( "-o", "--output"
        , dest     = "output"
        , help     = "Output file, mandatory"
        , required = True
        )
    cmd.add_argument \
        ( "parts"
        , help     = "Files to combine"
        , nargs    = '+'
        )
    args = cmd.parse_args ()
    if len (args.parts) < 2 :
        print ("Need at least 2 parts to combine", file=sys.stderr)
        return 1
    secrets = []
    for part in args.parts :
        f = open (part, "rb")
        secrets.append (f.read ())
        f.close ()
        if len (secrets) > 1 :
            if len (secrets [-2]) != len (secrets [-1]) :
                print ("Secrets need to be the same length", file=sys.stderr)
                return 1
    sp = Secret_Split (secrets = secrets)
    sp.combine ()
    f = open (args.output, "wb")
    f.write (sp.message)
    f.close ()
# end def main

sys.exit (main ())

