#!/usr/bin/python

import sys
import argparse
from secret_split import Secret_Split

def main () :
    cmd = argparse.ArgumentParser ()
    cmd.add_argument \
        ( "-n", "--number-of-parts"
        , dest     = 'nparts'
        , help     = "Number of secret parts to split into"
        , required = True
        , type     = int
        )
    cmd.add_argument \
        ( "-s", "--suffix"
        , dest     = 'suffix'
        , help     = "Suffix-format to append to message filename"
        , default  = '.part%d'
        )
    cmd.add_argument \
        ( "message"
        , help     = "File to split"
        )
    args = cmd.parse_args ()
    mf = open (args.message, "rb")
    sp = Secret_Split (message = mf.read ())
    mf.close ()
    sp.split (args.nparts)
    sp.combine () # assert that we get the message back
    for n, s in enumerate (sp.secrets) :
        fn = args.message + args.suffix % n
        f  = open (fn, "wb")
        f.write (s)
        f.close ()
# end def main

main ()

